# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-09 18:19
from __future__ import unicode_literals

from django.db import migrations, models
import pyuploadcare.dj.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(blank=True, max_length=255, null=True)),
                ('project_url', models.URLField(blank=True, max_length=100, null=True)),
                ('project_code', models.URLField(max_length=100)),
                ('project_screenshot', pyuploadcare.dj.models.ImageField(blank=True)),
                ('project_description', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
