# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-09 18:30
from __future__ import unicode_literals

from django.db import migrations, models
import pyuploadcare.dj.models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0003_technique'),
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('my_name', models.CharField(blank=True, max_length=100, null=True)),
                ('my_title', models.CharField(blank=True, max_length=250, null=True)),
                ('my_github', models.CharField(blank=True, max_length=80, null=True)),
                ('my_linkedin', models.CharField(blank=True, max_length=80, null=True)),
                ('my_email', models.EmailField(max_length=254)),
                ('my_image', pyuploadcare.dj.models.ImageField(blank=True)),
                ('pub_date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
