# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-26 05:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0004_info'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ('-id',)},
        ),
    ]
